/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceAssistantRouteImport } from './routes/voice-assistant'
import { Route as OfflineAppRouteImport } from './routes/offline-app'
import { Route as MicroinsuranceRouteImport } from './routes/microinsurance'
import { Route as CropQualityRouteImport } from './routes/crop-quality'
import { Route as ClimateRiskRouteImport } from './routes/climate-risk'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiRouteImport } from './routes/api/ai'

const VoiceAssistantRoute = VoiceAssistantRouteImport.update({
  id: '/voice-assistant',
  path: '/voice-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineAppRoute = OfflineAppRouteImport.update({
  id: '/offline-app',
  path: '/offline-app',
  getParentRoute: () => rootRouteImport,
} as any)
const MicroinsuranceRoute = MicroinsuranceRouteImport.update({
  id: '/microinsurance',
  path: '/microinsurance',
  getParentRoute: () => rootRouteImport,
} as any)
const CropQualityRoute = CropQualityRouteImport.update({
  id: '/crop-quality',
  path: '/crop-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ClimateRiskRoute = ClimateRiskRouteImport.update({
  id: '/climate-risk',
  path: '/climate-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/climate-risk': typeof ClimateRiskRoute
  '/crop-quality': typeof CropQualityRoute
  '/microinsurance': typeof MicroinsuranceRoute
  '/offline-app': typeof OfflineAppRoute
  '/voice-assistant': typeof VoiceAssistantRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/climate-risk': typeof ClimateRiskRoute
  '/crop-quality': typeof CropQualityRoute
  '/microinsurance': typeof MicroinsuranceRoute
  '/offline-app': typeof OfflineAppRoute
  '/voice-assistant': typeof VoiceAssistantRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/climate-risk': typeof ClimateRiskRoute
  '/crop-quality': typeof CropQualityRoute
  '/microinsurance': typeof MicroinsuranceRoute
  '/offline-app': typeof OfflineAppRoute
  '/voice-assistant': typeof VoiceAssistantRoute
  '/api/ai': typeof ApiAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/climate-risk'
    | '/crop-quality'
    | '/microinsurance'
    | '/offline-app'
    | '/voice-assistant'
    | '/api/ai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/climate-risk'
    | '/crop-quality'
    | '/microinsurance'
    | '/offline-app'
    | '/voice-assistant'
    | '/api/ai'
  id:
    | '__root__'
    | '/'
    | '/climate-risk'
    | '/crop-quality'
    | '/microinsurance'
    | '/offline-app'
    | '/voice-assistant'
    | '/api/ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClimateRiskRoute: typeof ClimateRiskRoute
  CropQualityRoute: typeof CropQualityRoute
  MicroinsuranceRoute: typeof MicroinsuranceRoute
  OfflineAppRoute: typeof OfflineAppRoute
  VoiceAssistantRoute: typeof VoiceAssistantRoute
  ApiAiRoute: typeof ApiAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-assistant': {
      id: '/voice-assistant'
      path: '/voice-assistant'
      fullPath: '/voice-assistant'
      preLoaderRoute: typeof VoiceAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline-app': {
      id: '/offline-app'
      path: '/offline-app'
      fullPath: '/offline-app'
      preLoaderRoute: typeof OfflineAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/microinsurance': {
      id: '/microinsurance'
      path: '/microinsurance'
      fullPath: '/microinsurance'
      preLoaderRoute: typeof MicroinsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-quality': {
      id: '/crop-quality'
      path: '/crop-quality'
      fullPath: '/crop-quality'
      preLoaderRoute: typeof CropQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/climate-risk': {
      id: '/climate-risk'
      path: '/climate-risk'
      fullPath: '/climate-risk'
      preLoaderRoute: typeof ClimateRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClimateRiskRoute: ClimateRiskRoute,
  CropQualityRoute: CropQualityRoute,
  MicroinsuranceRoute: MicroinsuranceRoute,
  OfflineAppRoute: OfflineAppRoute,
  VoiceAssistantRoute: VoiceAssistantRoute,
  ApiAiRoute: ApiAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
